/*---------------------------------------------------------------------------*
 * $Workfile: Init_OFDM_DSP.H $
 * Part of      : ETL600
 * Language     : C
 * Created by   : A. Gygax
 * Remarks      :
 * Purpose      :
 * Copyright    : ABB Switzerland Ltd., 2004
 *---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*
 * $Log: /Source/P4LT Prototype 2/OFDM_DSP/H/Init_OFDM_DSP.H $
 * 
 * 1     19.01.05 15:44 Chchlee
 * 
 * 2     15.06.04 14:04 Gygax02
 * 
 * 1     15.06.04 13:38 Gygax02
 *---------------------------------------------------------------------------*/

#ifndef INIT_OFDM_DSP_H
#define INIT_OFDM_DSP_H

/* INCLUDE FILES *************************************************************/
/* PUBLIC TYPE DECLARATIONS **************************************************/
/* PUBLIC CONSTANT DECLARATIONS **********************************************/
/* PUBLIC MACRO DEFINITIONS **************************************************/
/* PUBLIC FUNCTIONS **********************************************************/

void initialize_OFDM_DSP(void);

#endif

