#include "board.h"
#if BOARD==1
#define DRS7
#else
#undef DRS7
#endif
/******************************************************************************
 *
 * PROJECT     : OFDM Modem for ETL600  
 * FILE        : $Workfile: List_of_data_rates.h $
 * COPYRIGHT   : 2003 TL Consulting GmbH
 * DESCRIPTION : List of allowed data rates 
 *
 * REVISION HISTORY:
 *-----------------------------------------------------------------------------
 * 
 * 
 * Initial version
 *       22.04.2004 PL
 *****************************************************************************/
unsigned int segment ( "seg_extn_init" ) Size_Of_Rate_List = 30;
float        segment ( "seg_extn_init" ) List_of_data_rates[30]=
{
//#include "data_rate_list.dat"

// very save list: 10 elements (kein Bitstuffing notwendig, fuer L=N/8!, alle Bandbreiten)
// fuer FN=32kHz auch N/L: 64/16, 64/32, 128/8, 128/32, 256/8, 256/16, 256/64, 512/8, 512/16, 512/32
// all bit clocks are generated by core clock division!!!!
#ifdef DRS7
 
// 2400.0f ,
// 3200.0f ,
// 4000.0f ,
// 4800.0f ,
// 6000.0f ,
// 6400.0f ,
// 8000.0f ,
// 9600.0f ,
 12000.0f ,
// 12800.0f ,
 16000.0f ,
// 19200.0f ,
 24000.0f ,
// 25600.0f ,
 32000.0f ,
// 38400.0f ,
 48000.0f ,
// 51200.0f ,
 64000.0f ,
// 76800.0f ,
 96000.0f ,
// 102400.0f ,
 128000.0f ,
// 153600.0f ,
 192000.0f ,
// 204800.0f ,
 256000.0f 
    // number of elements mus be even, if not copy last element

#else

/*
// save list: 20 elements (kein Bitstuffing notwendig, fuer L=N/8!, alle Bandbreiten)
// fuer FN=32kHz auch N/L: 64/16, 64/32, 128/8, 128/32, 256/8, 256/16, 256/64, 512/8, 512/16, 512/32
// !!!! external synthesizer required to generate all bit clocks !!!!
12000.0f ,
 16000.0f ,
 24000.0f ,
 32000.0f ,
 36000.0f ,
 40000.0f ,
 48000.0f ,
 56000.0f ,
 64000.0f ,
 72000.0f ,
 80000.0f ,
 96000.0f ,
112000.0f , 
128000.0f ,
144000.0f ,
160000.0f ,
192000.0f ,
224000.0f ,
256000.0f ,
256000.0f    // number of elements mus be even, if not copy last element
*/

/*
// full list: 26 elements (alle aus Benninger Reihe 1 und 2)
// kein Bit-Stuffing fuer Fn=32kHz bei N/L: 64/16, 128/32, 256/64, 512/8
 9600.0f ,
 12000.0f ,
 14400.0f ,
 16000.0f ,
 19200.0f ,
 24000.0f ,
 28800.0f ,
 32000.0f ,
 36000.0f ,
 38400.0f ,
 40000.0f ,
 48000.0f ,
 56000.0f ,
 64000.0f ,
 72000.0f ,
 76800.0f ,
 80000.0f ,
 96000.0f ,
112000.0f , 
128000.0f ,
144000.0f ,
153600.0f ,
160000.0f ,
192000.0f ,
224000.0f ,
256000.0f    // number of elements mus be even, if not copy last element
*/


// full2 list: 29 elements (alle aus Benninger Reihe 1 und 2)
// kein Bit-Stuffing fuer Fn=32kHz bei N/L: 64/16, 128/32, 256/64, 512/8
 9600.0f ,
 12000.0f,
 14400.0f,
 16000.0f,
 19200.0f,
 24000.0f,
 28800.0f,
 32000.0f,
 36000.0f,
 38400.0f,
 40000.0f,
 48000.0f,
 56000.0f,
 64000.0f,
 72000.0f,
 76800.0f,
 80000.0f,
 96000.0f,
112000.0f, 
128000.0f,
144000.0f,
153600.0f,
160000.0f,
192000.0f,
224000.0f,
256000.0f,    
288000.0f,
307200.0f,
320000.0f,
320000.0f    // number of elements mus be even, if not copy last element


#endif



};


