/*-------------------------------------------------------------------------*
 * $Workfile	: Patch_CRC_Into_Loaderfile.h $
 * Part of		: ETL600 / O4CV
 * Language		: C
 * Created by	: Allen Notter (AN)
 * Remarks		:  
 * Purpose		: Patch crc into loaderfile
 * Copyright    : ABB Switzerland Ltd., 2007
 *-------------------------------------------------------------------------*/
/*-------------------------------------------------------------------------*
 * $Log: /branches/Source O4CV/O4CV/Tools/ChecksumPatcher/Patch_CRC_Into_Loaderfile.H $
 * 
 * 1     07-08-30 10:39 Chalnot
 * Initial version.
 * 
 * 
 *-------------------------------------------------------------------------*/

#ifndef PATCH_CRC_INTO_LOADERFILE
#define PATCH_CRC_INTO_LOADERFILE

/* INCLUDE FILES **************************************************************/

/* PUBLIC CONSTANT DECLARATIONS ***********************************************/

/* PUBLIC TYPE DECLARATIONS ***************************************************/

/* PUBLIC MACRO DEFINITIONS ***************************************************/

/* PUBLIC FUNCTIONS ***********************************************************/

#endif

