/*-------------------------------------------------------------------------*
 * $Workfile: BLOCKS.H $
 * Part of	: LCPLC
 * Language	: C
 * Created by	: CLEMENS BUERGI    12.03.1998
 * Remarks	:     
 * Purpose	:     Defines for parameter and event block handling
 *-------------------------------------------------------------------------*/
                                 
/*-------------------------------------------------------------------------*
 * $Log: /Source/P4LT Prototype 2/Master_DSP/H/BLOCKS.H $  
 * 
 * 1     19.01.05 15:49 Chchlee
 * 
 * 2     15.12.04 10:18 Chchlee
 * 
 * 1     10.03.04 12:14 Nohl01
 * Initial version
 * Based on MMI500 v. 3.20
 *-------------------------------------------------------------------------*/ 
 
 #ifndef _BLOCKS
 #define _BLOCKS
 
 //#define EVENT_BLOCK		0xF0
 //#define PARAM_BLOCK		0x0F
 //#define EMPTY_BLOCK        0x10
 //#define NOT_MARKED			0xFF  
 
/*
 typedef struct  
 {     
	long *Address;
	long Size;	             
 }ConfigStructsListStruc; 
 */
 //#define DATA_OFFSET        0x08
 //#define EVENTDATA_OFFSET   0x10
 
 //#define NO_BLOCK_AVAILABLE 0x01
 //#define OK					0x0
 
 #endif


