/*---------------------------------------------------------------------------*
 * $Workfile: Init_Master_DSP.H $
 * Part of      : ETL600
 * Language     : C
 * Created by   : H.P. Rytz
 * Remarks      :
 * Purpose      :
 * Copyright    : ABB Switzerland Ltd., 2004
 *---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*
 * $Log: /Source/P4LT Prototype 2/Master_DSP/H/Init_Master_DSP.H $
 * 
 * 1     19.01.05 15:50 Chchlee
 * 
 * 3     16.06.04 17:17 Rytz01
 * 
 * 2     3.06.04 17:33 Rytz01
 * Initial version
 * 
 * 1     3.06.04 16:37 Rytz01
 *---------------------------------------------------------------------------*/

#ifndef INIT_MASTER_DSP_H
#define INIT_MASTER_DSP_H

/* INCLUDE FILES *************************************************************/
/* PUBLIC TYPE DECLARATIONS **************************************************/
/* PUBLIC CONSTANT DECLARATIONS **********************************************/
/* PUBLIC MACRO DEFINITIONS **************************************************/
/* PUBLIC FUNCTIONS **********************************************************/

void initialize_DSP(void);
void Init_DSP_Register(void);


#endif

